export type Project = {
  id: number;
  name: string;
  tagline: string;
  bullets: string[];
  techStack: string[];
  keyMetric: string;
  repoUrl: string;
  gradient: string;
};

export const projects: Project[] = [
  {
    id: 1,
    name: "Documentary Factory",
    tagline: "Full-length documentaries generated by AI agents",
    bullets: [
      "8 coordinated ReAct agents (Research, Script, Audio, Video, Music, Editing, QA) collaborate end-to-end to produce complete documentary videos automatically.",
      "Checkpoint/resume system saves pipeline state after each agent step, enabling crash recovery without re-running completed work.",
      "AI vision review with GPT-4o validates every stock footage clip for scene relevance before inclusion in the final cut.",
    ],
    techStack: ["Python", "GPT-4o", "MoviePy", "FFmpeg", "Edge-TTS", "Pexels API", "Freesound"],
    keyMetric: "~$0.03–0.05 per 10-min documentary",
    repoUrl: "https://github.com/Rutvik552k/documentry-factory",
    gradient: "from-purple-600 to-blue-600",
  },
  {
    id: 2,
    name: "Reel Factory",
    tagline: "AI content engine for Reels, YouTube & quote images",
    bullets: [
      "Generates Instagram Reels (9:16), YouTube documentaries (16:9), and viral quote images from a single text prompt.",
      "Kokoro 82M TTS runs on CPU-only for cost-free voiceover in English and Hindi with natural prosody.",
      "Celery + Redis task queue enables batch generation with auto-publish to Instagram via the Graph API.",
    ],
    techStack: ["FastAPI", "Celery", "Redis", "Kokoro TTS", "MoviePy", "AWS S3", "Instagram API"],
    keyMetric: "Multi-format, multi-language, fully automated",
    repoUrl: "https://github.com/Rutvik552k/reel-factory",
    gradient: "from-pink-600 to-orange-500",
  },
  {
    id: 3,
    name: "Persona-Switching Agent",
    tagline: "Dynamic persona chatbot with LangGraph state machine",
    bullets: [
      "4-node LangGraph state machine (initialize → validate → handle persona → execute chat) auto-detects profession from user messages.",
      "Generates role-specific system prompts on-the-fly and caches them in PostgreSQL for instant recall on subsequent conversations.",
      "Streamlit UI with per-profession conversation threads in the sidebar for seamless multi-persona interaction.",
    ],
    techStack: ["FastAPI", "LangGraph", "PostgreSQL", "Streamlit", "OpenAI"],
    keyMetric: "4-node state machine, auto persona detection",
    repoUrl: "https://github.com/Rutvik552k/persona-switching-agent",
    gradient: "from-cyan-500 to-teal-500",
  },
  {
    id: 4,
    name: "CRM Project",
    tagline: "Full-stack customer relationship management system",
    bullets: [
      "End-to-end CRM for managing customer interactions, sales pipelines, and business relationships.",
      "Integrated AI layer for intelligent insights and automated follow-up recommendations.",
      "Full-stack architecture with JavaScript frontend and Python backend for data processing.",
    ],
    techStack: ["JavaScript", "Python", "HTML", "CSS"],
    keyMetric: "Full-stack JS + Python CRM",
    repoUrl: "https://github.com/Rutvik552k/crmproject",
    gradient: "from-emerald-500 to-green-600",
  },
  {
    id: 5,
    name: "Cold Reach AI",
    tagline: "AI-powered cold outreach automation",
    bullets: [
      "Automates prospect research by crawling public data sources and extracting entity profiles at scale.",
      "LLM-generated personalized messaging tailored to each prospect's role, company, and pain points.",
      "End-to-end pipeline from lead discovery to outreach execution for targeted B2B campaigns.",
    ],
    techStack: ["JavaScript", "Python", "HTML", "CSS"],
    keyMetric: "Automated prospect research + outreach",
    repoUrl: "https://github.com/Rutvik552k/cold-reach-ai",
    gradient: "from-amber-500 to-red-500",
  },
];
